# Generated by Django 5.0.2 on 2024-03-04 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calchistory',
            name='saved_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
